import type { ContentBlockParam, ImageBlockParam } from '@anthropic-ai/sdk/resources'
import type { ChatAttachment, SelectionSummary } from '../../shared/ipc'

/**
 * Extra context appended to the `claude_code` preset system prompt (see
 * `systemPrompt: { type: 'preset', preset: 'claude_code', append: ... }` in
 * session.ts). Orients Claude inside the Voyager AI desktop app and points
 * it at the printable-cad skill and the project's working directory.
 */
export function systemPromptAppend(projectDir: string): string {
  return [
    'You are the modeling engine inside Voyager AI, a desktop app for 3D-printing hobbyists.',
    'The user sees your replies in a chat panel next to a live 3D viewport - keep replies',
    'conversational and compact; you are not writing documentation.',
    '',
    `Your project working directory (cwd) is \`${projectDir}\`. It already contains an` +
      ' `./outputs/` directory and a project-local copy of the printable-cad skill' +
      ' (installed under `.claude/skills/printable-cad`).',
    '',
    'ALWAYS follow the printable-cad skill\'s phased workflow for any part-modeling request -',
    'it is installed in this project and takes priority over improvising. Save every artifact to',
    '`./outputs/` with a version suffix (`<part>_vN.py`, `<part>_vN.stl`, `<part>_vN.step`) so',
    'earlier iterations are never overwritten.',
    '',
    'After every successful export + validation (Phase 5 of the skill), call the `display_model`',
    'MCP tool so the model appears in the user\'s viewport - never generate `viewer.html`, Voyager',
    'has its own native viewer. Call `set_status` for brief progress notes on longer steps (running',
    'the script, validating the mesh) so the user isn\'t staring at a blank chat.',
    '',
    'When the user asks for print settings or slicer settings for the current model, call the',
    '`recommend_print_settings` MCP tool (skill Phase 7) instead of just replying in prose - it',
    'renders as a list in Voyager\'s print-settings panel.',
    '',
    'The user cannot run commands themselves - you run everything (the script, the validator, etc.)',
    'on their behalf. `python` on PATH is Voyager\'s managed CAD environment with build123d, trimesh,',
    'and numpy pre-installed; use it directly.',
    '',
    'The user may highlight a region of the currently displayed model. When they do, their next',
    'message will include a "Selected region" context block (bounding box, centroid, size, triangle',
    'count) generated by the viewport, not typed by the user - correlate it with the current',
    'parametric script to figure out which feature they mean, per the skill\'s Phase 6 guidance.'
  ].join('\n')
}

/**
 * Formats a `SelectionSummary` (a highlighted viewport region) into the
 * "Selected region" context block the printable-cad skill expects to find
 * appended to the user's message (see SKILL.md Phase 6).
 */
export function formatSelectionContext(selection: SelectionSummary): string {
  const fmt = (n: number): string => n.toFixed(2)
  const [minX, minY, minZ] = selection.bboxMin
  const [maxX, maxY, maxZ] = selection.bboxMax
  const [cx, cy, cz] = selection.centroid
  const [dx, dy, dz] = selection.dims

  return [
    '--- Selected region (from viewport, not typed by the user) ---',
    `Bounding box min: (${fmt(minX)}, ${fmt(minY)}, ${fmt(minZ)}) mm`,
    `Bounding box max: (${fmt(maxX)}, ${fmt(maxY)}, ${fmt(maxZ)}) mm`,
    `Centroid: (${fmt(cx)}, ${fmt(cy)}, ${fmt(cz)}) mm`,
    `Dimensions (W x D x H): ${fmt(dx)} x ${fmt(dy)} x ${fmt(dz)} mm`,
    `Triangle count: ${selection.triCount}`,
    'Correlate this region with the current parametric script\'s geometry (by position and size)' +
      ' to identify which named feature the user means; confirm your interpretation before' +
      ' regenerating if there is any ambiguity.'
  ].join('\n')
}

/**
 * Combines the user's typed text with a formatted selection context block
 * (if a region is highlighted) into the user turn's message content. Stays a
 * plain string when there are no attachments (matching every message before
 * this feature existed); only becomes a content-block array - images first,
 * so the following text block can refer to "the image above" - when the user
 * attached at least one image.
 */
export function buildUserMessage(
  text: string,
  selectionContext?: SelectionSummary | null,
  attachments?: ChatAttachment[]
): string | ContentBlockParam[] {
  const combined = selectionContext ? `${text}\n\n${formatSelectionContext(selectionContext)}` : text
  if (!attachments || attachments.length === 0) return combined

  const imageBlocks: ImageBlockParam[] = attachments.map((attachment) => ({
    type: 'image',
    source: { type: 'base64', media_type: attachment.mediaType, data: attachment.data }
  }))
  return [...imageBlocks, { type: 'text', text: combined }]
}
