import type { ContentBlockParam, ImageBlockParam } from '@anthropic-ai/sdk/resources'
import type { ChatAttachment, SelectionSummary } from '@shared/ipc'
import type { ProjectIteration } from '../projects/store'

/**
 * Extra context appended to the `claude_code` preset system prompt (see
 * `systemPrompt: { type: 'preset', preset: 'claude_code', append: ... }` in
 * session.ts). Orients Claude inside the Voyager AI desktop app and points
 * it at the printable-cad skill and the project's working directory.
 */
export function systemPromptAppend(projectDir: string): string {
  return [
    'You are the modeling engine inside Voyager AI, a desktop app for 3D-printing hobbyists.',
    'The user sees your replies in a chat panel next to a live 3D viewport - keep replies',
    'conversational and compact; you are not writing documentation.',
    '',
    `Your project working directory (cwd) is \`${projectDir}\`. It already contains an` +
      ' `./outputs/` directory and a project-local copy of the printable-cad skill' +
      ' (installed under `.claude/skills/printable-cad`).',
    '',
    'ALWAYS follow the printable-cad skill\'s phased workflow for any part-modeling request -',
    'it is installed in this project and takes priority over improvising. Save every artifact to',
    '`./outputs/` with a version suffix (`<part>_vN.py`, `<part>_vN.stl`, `<part>_vN.step`) so',
    'earlier iterations are never overwritten.',
    '',
    'Alongside the chat, the user sees a live Design Brief panel - the structured, machine-checkable',
    'spec (part identity, envelope, features, materials, constraints, exclusions, acceptance',
    'criteria) that gates generation and later verification. During Phase 2 (specify the part), call',
    'the `update_brief` MCP tool as soon as you confirm a field with the user - don\'t hold it all in',
    'your own context until the end; the panel should fill in live as the conversation progresses.',
    'Every value you set through `update_brief` is recorded with "inferred" provenance and renders',
    'distinctly in the panel until the user confirms it or edits it directly - you never get to mark',
    'a field as user-confirmed yourself. Phase 4 (generating code) requires a locked brief: the user',
    'locks it from the panel, which also sends you a message telling you it\'s locked so you can',
    'proceed. If the user asks you to generate before that message arrives, tell them to review and',
    'lock the brief in the panel first rather than generating against an unlocked one.',
    '',
    'After every successful export + validation (Phase 5 of the skill), call the `display_model`',
    'MCP tool so the model appears in the user\'s viewport - never generate `viewer.html`, Voyager',
    'has its own native viewer. Call `set_status` for brief progress notes on longer steps (running',
    'the script, validating the mesh) so the user isn\'t staring at a blank chat.',
    '',
    'When the user asks for print settings or slicer settings for the current model, call the',
    '`recommend_print_settings` MCP tool (skill Phase 7) instead of just replying in prose - it',
    'renders as a list in Voyager\'s print-settings panel.',
    '',
    'The user cannot run commands themselves - you run everything (the script, the validator, etc.)',
    'on their behalf. `python` on PATH is Voyager\'s managed CAD environment with build123d, trimesh,',
    'and numpy pre-installed; use it directly.',
    '',
    'The user may highlight a region of the currently displayed model. When they do, their next',
    'message will include a "Selected region" context block (bounding box, centroid, size, triangle',
    'count) generated by the viewport, not typed by the user - correlate it with the current',
    'parametric script to figure out which feature they mean, per the skill\'s Phase 6 guidance.',
    '',
    'Every displayed version is snapshotted to `./outputs/versions/vN.py` (an exact copy of the',
    'script that produced version N). The user can revert to an earlier version; when they do, their',
    'next message will include a "Reverted model" context block naming that version and its',
    '`./outputs/versions/vN.py` script. Treat that script as the current source of truth: copy it',
    'forward to the next `<part>_vN.py` and modify that, rather than continuing from a later version',
    'you generated earlier - the user has intentionally branched back to it.'
  ].join('\n')
}

/**
 * Formats a `SelectionSummary` (a highlighted viewport region) into the
 * "Selected region" context block the printable-cad skill expects to find
 * appended to the user's message (see SKILL.md Phase 6).
 */
export function formatSelectionContext(selection: SelectionSummary): string {
  const fmt = (n: number): string => n.toFixed(2)
  const [minX, minY, minZ] = selection.bboxMin
  const [maxX, maxY, maxZ] = selection.bboxMax
  const [cx, cy, cz] = selection.centroid
  const [dx, dy, dz] = selection.dims

  return [
    '--- Selected region (from viewport, not typed by the user) ---',
    `Bounding box min: (${fmt(minX)}, ${fmt(minY)}, ${fmt(minZ)}) mm`,
    `Bounding box max: (${fmt(maxX)}, ${fmt(maxY)}, ${fmt(maxZ)}) mm`,
    `Centroid: (${fmt(cx)}, ${fmt(cy)}, ${fmt(cz)}) mm`,
    `Dimensions (W x D x H): ${fmt(dx)} x ${fmt(dy)} x ${fmt(dz)} mm`,
    `Triangle count: ${selection.triCount}`,
    'Correlate this region with the current parametric script\'s geometry (by position and size)' +
      ' to identify which named feature the user means; confirm your interpretation before' +
      ' regenerating if there is any ambiguity.'
  ].join('\n')
}

/**
 * Formats the "Reverted model" context block injected into the user's turn
 * while they are sitting on an earlier version (their `activeIteration` is
 * behind the latest recorded one). Tells the agent which version is current
 * and, crucially, which on-disk script produced it, so further edits branch
 * from that script instead of the superseded later versions. Uses the
 * app-controlled `scriptSnapshotPath` (guaranteed to match the STL) when
 * present, falling back to the agent-written `scriptPath` for older records.
 */
export function formatRevertContext(active: ProjectIteration, latestN: number): string {
  const script = active.scriptSnapshotPath ?? active.scriptPath
  const supersededRange =
    active.n + 1 === latestN ? `v${latestN}` : `v${active.n + 1}-v${latestN}`
  return [
    '--- Reverted model (from Voyager, not typed by the user) ---',
    `The user reverted to model v${active.n}. It is the currently displayed version.`,
    `The script that produced it is \`${script}\`.`,
    `Base any further changes on that script - copy it forward to the next \`<part>_vN.py\` and`,
    `modify that. Do NOT continue from the now-superseded later versions (${supersededRange}); the`,
    'user has intentionally branched back to this one.'
  ].join('\n')
}

/**
 * Combines the user's typed text with formatted context blocks - a highlighted
 * selection region and/or a "Reverted model" notice (both optional, both can be
 * present) - into the user turn's message content. Stays a plain string when
 * there are no attachments (matching every message before this feature
 * existed); only becomes a content-block array - images first, so the following
 * text block can refer to "the image above" - when the user attached at least
 * one image.
 */
export function buildUserMessage(
  text: string,
  selectionContext?: SelectionSummary | null,
  attachments?: ChatAttachment[],
  revertContext?: string | null
): string | ContentBlockParam[] {
  const blocks = [text]
  if (selectionContext) blocks.push(formatSelectionContext(selectionContext))
  if (revertContext) blocks.push(revertContext)
  const combined = blocks.join('\n\n')
  if (!attachments || attachments.length === 0) return combined

  const imageBlocks: ImageBlockParam[] = attachments.map((attachment) => ({
    type: 'image',
    source: { type: 'base64', media_type: attachment.mediaType, data: attachment.data }
  }))
  return [...imageBlocks, { type: 'text', text: combined }]
}
